# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_udemy
    volumes:
      - "./volume-bd-mysql:/var/lib/mysql"