spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.21.0.2:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  flyway:
    schemas: rest_with_spring_boot_udemy
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

    spring:
      flyway:
        schemas=charge_engine_action: